// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfltmlqbasfdlzmxjykw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbHRtbHFiYXNmZGx6bXhqeWt3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzg4MzQsImV4cCI6MjA2ODgxNDgzNH0.O3V2h4NmuyV1WxfNooAu_bDPaKfvuKwSq3rRFKbCcE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});